name: Cancel
on:
  workflow_run:
    workflows: ["main", "eslint", "bandit", "pylint"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
        workflow_id: ${{ github.event.workflow.id }}
